version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: visualize-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
