name: CI Pipeline - Test, Build & Push

on:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Executar testes com pytest
        run: pytest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Definir tags da imagem
        id: meta
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/visualize-api
          SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "tags=latest,${SHA}" >> $GITHUB_OUTPUT

      - name: Build e Push da imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.image }}:latest
            ${{ steps.meta.outputs.image }}:${{ github.sha }}
